sudo: false

language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - test -z "$(gofmt -s -l $(find . -name '*.go' -type f -print) | tee /dev/stderr)"
  - go vet
  - go test -v ./...
  - go test -race -v ./...
